apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
type: Opaque
data:
  # These should be base64 encoded values
  # github-token: <base64-encoded-github-token>
  # dockerhub-username: <base64-encoded-username>
  # dockerhub-password: <base64-encoded-password>